### ISSUE TITLE
Search error has fixed url and does not allow for refresh

### ISSUE THREAD

**Issue by raedah** [dcrdata/dcrdata#261]
Upon doing a failed search, the user is returned to a url that looks like this
https://explorer.dcrdata.org/error/.......
When the user does a page refresh to check if the address or hash is now valid, they will always get the same error page regardless of if new data is available.
The expected behavior is for a page refresh to trigger the search again.

**Comment by ugwuchuks** [comment]
/home/chucks/Downloads/dcrdata-address-cache-correct error/error.go

**Comment by raedah** [comment]
Bug in this, search is often not working on the first attempt, returning back to the same page. Usually works on the second attempt. For the current red highlighting, it does no work for user with javascript disabled, and it also does not clearly state to the user what is happening, "A transaction with id xxx could not be found." For the page that is displaying that error, it should use web sockets to refresh as soon as the transaction does become available. This should be applied to transactions and all other searchable types.

**Comment by RogueElement** [comment]
The first attempt bug is probably due to the search occurring before the websocket connection is fully established. I dont know where to put the error message it should show which is why I just went with the red highlight. I can probably try something for the no javascript case like falling back to the url `/search`.
