### ISSUE TITLE
removing /explorer/ from the url

### ISSUE THREAD

**Issue by raedah** [dcrdata/dcrdata#282]
Having the extra word in the url is redundant and makes the url longer.
https://explorer.dcrdata.org/explorer/block/187492
https://explorer.dcrdata.org/block/187492   would be better.
https://dcrdata.org/block/187492   would be even shorter.

**Comment by xaur** [comment]
Also please https://explorer.dcrdata.org/explorer -> https://explorer.dcrdata.org/blocks

**Comment by RogueElement** [comment]
Would need to merge explorer and the root page for this to work.

**Comment by raedah** [comment]
I like @xaur's idea of making /explorer into /blocks , more descriptive of the element that is actually being shown. Id like dcrdata.org to be identical to explorer.dcrdata.org instead of forwarding to it so that sharing urls would stay compact.

**Comment by chappjc** [comment]
- I agree that /explorer, which currently shows a list of blocks, should be at /blocks.
- Root page is good as the root page.
- A specific block's page should go from /explorer/block/190365 to /blocks/190365.
- The other pages are good, just without the /explorer prefix.

**Comment by xaur** [comment]
If you plan to deploy other apps on dcrdata.org domain, better keep explorer subdomain.

**Comment by xaur** [comment]
There is a consistency concern regarding singular vs plural form.

Popular explorers use singular form:

https://blockchain.info/block/0000000000000000007f6c84ee3f61cb0d897a928cf29c590645bdef447d0d6f
https://blockchain.info/tx/b1606386935bdad97b017c215ce9a7c35dd4e25fc26de7a5c0a75680c5337070
https://blockchain.info/address/18cBEMRxXHqzWWCxZNtU91F5sbUNKhL5PX

https://mainnet.decred.org/address/DsUBWJgJheWPQynZ4nqRXTTPvVTx3aDkPci
https://mainnet.decred.org/tx/98580b8a092b8258b6e0f8c90b89f402ca58b65730709130ddb2398b70806fb7
https://mainnet.decred.org/address/DsmM7jVwRsBk21rLK4QyUywiNDALZfk54G7

https://www.coinprism.info/block/0000000000000000002dc1a21e0c24645a434b49aed634008ab362c4c74ebbd2
https://www.coinprism.info/tx/9232d9e3cac93cf34f5f9f34293fff32c6188bcb1269880cc8f5d4cb999b4c84
https://www.coinprism.info/address/19y9cs7ffYLpJ15Y299KZXhsRWc8gzfzgC

.. and so on.

If you use /blocks/x, then for (local) consistency within dcrdata explorer plural form should be used in other places, e.g. /addresses/x (/tx may just work since its an abbreviation). This is more in line with [REST collection naming](https://en.wikipedia.org/wiki/Representational_state_transfer#Relationship_between_URL_and_HTTP_methods), but perhaps does not matter much for non-API URLs.

Personally, I would go with the crowd.

**Comment by chappjc** [comment]
@xaur Thanks for your input on this issue.  Regarding the API, we should definitely ensure plural us used wherever it makes sense.  Admittedly, I have not been consistent.

As far as the HTML pages are concerned, I'm not particularly dogmatic about any given solution, except for self-consistency.

In general, I strongly believe we should prioritize:

1. what make sense
2. what makes routing less compless
3. what others do

Let's not be afraid to go against the crowd when is makes sense to do so.

**Comment by chappjc** [comment]
Before someone cooks up a PR for this.  Let's see a thorough proposal for all the URLs.

**Comment by RogueElement** [comment]
`/` -> `/`
`/explorer` -> `/blocks`
`/explorer/block/x` -> `/blocks/x`
`/explorer/tx/x` -> `/tx/x`
`/explorer/address/x` -> `/address/x`
`/explorer/decodetx` -> `/decodetx`
Will need to export the path contexts but this could work.

**Comment by chappjc** [comment]
There may be a need to have an `/addresses` page.  There is a variety of data we can report: number of known addresses, utxos by address, balance stats, etc.  Of course this could just be called something else when we get around to it.

**Comment by RogueElement** [comment]
So are we okay on the new urls?

**Comment by chappjc** [comment]
Sure.  We'll rework the API URLs in a separate PR
