### ISSUE TITLE
web interface

### ISSUE THREAD

**Issue by chappjc** [dcrdata/dcrdata#6]
we probably need one

Should it be:

1. A separate process getting data through the API and/or our own RPC, or
2. Part of the same process that serves the API and manages the data and actual communication with dcrd?

**Comment by raedah** [comment]
yes, we need a browsable web interface to complement the api. Id go with in the same process since the web interface code should be easily compartmentalized within the project and will share the rest of the code with the api. Should use the same functions (and data sources) for retrieving the data as the api. Likewise, everything viewable on the web interface should be accessible via the api. Minimal design but good hyperlinking connection of the data on the initial templates.

**Comment by chappjc** [comment]
Closed by https://github.com/dcrdata/dcrdata/pull/14, but that's just a start.
